export const POS = [
  "Abacus Solutions",
  "Accent IT Services Ltd.",
  "Acrelec",
  "Aibesoft",
  "Aldelo POS",
  "Auphan Software",
  "BEST POS (logiciel)",
  "CAP INFO",
  "Carrepos",
  "Cashpad",
  "Cassa in Cloud - Twinlogix",
  "Centrix",
  "CloudPOS",
  "Clover",
  "Cluster POS",
  "Clyo Systems",
  "Codisys",
  "Compucash",
  "Countr",
  "Datasym UK Ltd",
  "DCS Technologies (Ranger POS)",
  "Delivery Manager App (DMA)",
  "Easy POS (IT4Merchant Solution LTD)",
  "EasyRest by Zeshop",
  "Easyshop/Easystore by Advensys ",
  "Emperium POS",
  "Epos Now",
  "Foodics",
  "force7web",
  "GASTROFIX",
  "Givex",
  "Glop",
  "GRUBBRR",
  "Grupo Sime",
  "Guestline Ltd",
  "HI-IBERIA - HIPPOS",
  "Hippos (NoAm)",
  "Hostedkitchens",
  "Hypersoft",
  "IBS / Access Group",
  "ICRTouch",
  "IGT (Agora)",
  "iiko",
  "iKentoo",
  "iPratico",
  "J Restaurant POS",
  "k-robo",
  "KOBAS",
  "Kounta",
  "L'Addition",
  "Lightspeed",
  "Maitre'D Posera",
  "Mealsy",
  "Menlog",
  "Mercurio Sistemi",
  "Micros RES 3700",
  "Micros Simphony",
  "MicroSys Technology Company - POS",
  "Miss Tipsi",
  "MobiPOS",
  "My Order Box",
  "Mycheftool",
  "NationalSoft (SoftRestaurant version 10)",
  "NCR",
  "Next Order",
  "Nextt",
  "Nomee",
  "Novasoft FZCO",
  "Nōwn",
  "Omega POS",
  "OneContact POS (Topaz)",
  "Onlinepos A/S (POS)",
  "PAR tech - Brink",
  "PixelPoint PAR Tech",
  "PointOne",
  "POSist Technologies",
  "POSist Technologies - Cloud system",
  "Prefectos",
  "Presto Express (Firefly Apps)",
  "Pro Dukaan (HungryByte)",
  "Prologicfirst",
  "QuickPOS Technologies Inc.",
  "Rest Pro (Ambit Technology) - POS MX",
  "Revel Systems",
  "Revo",
  "Sapaad",
  "Scloby",
  "SilverWare POS",
  "SmilePOS",
  "Softabacus UK Ltd",
  "Softcaisse by AMI-WEB",
  "Solutions 4 Delivery",
  "Spont.cash",
  "Square",
  "Storyous",
  "Surpass Everyware Business Solutions",
  "SYMBIOZ",
  "Tabletop Group",
  "Tango Speed",
  "TCPOS",
  "Tevalis",
  "The Cloud",
  "Tiller",
  "Tissl Ltd",
  "TouchBistro",
  "Trivec",
  "Twirll",
  "untill",
  "Veloce POS",
  "Vista Entertainment Solutions Ltd.",
  "WaiterPro",
  "Xperiopos",
  "Xudox",
  "zeshop",
  "Zonal",
];

export const venueTypes = [
  "Airport Lounges",
  "Restaurant",
  "Bar",
  "Café",
  "Pub",
  "Food truck",
  "Theatre",
  "Music venue",
  "School canteen",
  "Office canteen",
  "Coffee Shops",
  "Nightclubs",
  "Outdoor venues",
];
